name: CI
on: push

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules Init
      uses: snickerbockers/submodules-init@v4
    - name: Install xorg-dev
      run: sudo apt install xorg-dev
    - name: Build Debug
      run: ./build.sh
    - name: Build Release
      run: ./buildRelease.sh
  macOS-build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2    
    - name: Submodules Init
      uses: snickerbockers/submodules-init@v4
    - name: Build Debug
      run: ./build.sh
    - name: Build Release
      run: ./buildRelease.sh
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Submodules Init
      uses: snickerbockers/submodules-init@v4
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build Debug
      run: |
        cmake --config=Debug .
        msbuild Shards.sln
    - name: Build Release
      run: |
        cmake --config=Release .
        msbuild Shards.sln
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
    - name: Build Debug
      run: |
          ./buildDocker.sh
    - name: Build Release
      run: |
          ./buildDockerRelease.sh
