name: CI
on: push

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      run: ./build.sh
    - name: Test Debug
      run: |
        cd build
        ctest -j$(nproc)
    - name: Build Release
      run: ./buildRelease.sh
    - name: Test Release
      run: |
        cd buildRelease
        ctest -j$(nproc)
  macOS-build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Debug
      run: ./build.sh
    - name: Test-Debug
      run: |
        cd build
        ctest -j$(nproc)
    - name: Build Release
      run: ./buildRelease.sh
    - name: Test Release
      run: |
        cd buildRelease
        ctest -j$(nproc)
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Build Debug
      run: build.bat
    - name: Test Debug
      run: |
        cd build
        ctest -j2
    - name: Build Release
      run: buildRelease.bat
    - name: Test Release
      run: |
        cd buildRelease
        ctest -j2
